#define KAsal(p) p->KAsal
#define NextVertex(p) p->NextVertex
//#define Connect(p) p->Connect
#define HeadVtx(H) ((H).HeadVtx)
#define Kode(p) p->Kode
#define KOTA(p) p->KOTA
#define NamaKota(p) p->NamaKota
#define NextKKota(p) p->NextKKota
#define firstKKota(H) ((H).firstKKota)
#define Departure(p) p->Departure
#define KodeDpr(p) p->KodeDpr
#define Arrival(p) p->Arrival
#define KodeArv(p) p->KodeArv
#define NamaPesawat(p) p->NamaPesawat
#define KodePesawat(p) p->KodePesawat
#define Timedeparture(p) p->Timedeparture
#define Timearrival(p) p->Timearrival
#define Durasi(p) p->Durasi
#define Harga(p) p->Harga
#define NextIE(p) p->NextIE
#define FirstIE(H) ((H).FirstIE)
#define FirstPTr(H) ((H).FirstPTr)
#define firstEdge(p) p->firstEdge
#define infotypepenerbangan(p) p->infotypepenerbangan
#define NextEdge(p) p->NextEdge
#define ConnectVertex(p) p->ConnectVertex
#define IEd(p) p->IEd
#define DPT(p) p->DPT
#define KDPT(p) p->KDPT
#define ARV(p) p->ARV
#define KARV(p) p->KARV
#define firstInfo(p) p->firstInfo
#define visit(p) p->visit
#define No_Jadwal(p) p->No_Jadwal
#define NextQ(p) p->NextQ
#define NextS(p) p->NextS
#define NextFlight(p) p->NextFlight
#define Head(H) ((H).Head)
#define Tail(H) ((H).Tail)
#define Top(H) ((H).Top)
#define firstFlight(H) ((H).firstFlight)
#define FirstTDFS(H) ((H).FirstTDFS)
#define FirstPlg(H) ((H). FirstPlg)
#define FirstVstd(H) ((H). FirstVstd)
#define FirstPenTransit(H) ((H). FirstPenTransit)
#define NamaPemesan(p) p->NamaPemesan
#define NomorHp(p) p->NomorHp
#define Asal(p) p->Asal
#define Tujuan(p) p->Tujuan
#define Maskapai(p) p->Maskapai
#define KodePes(p) p->KodePes
#define TBerangkat(p) p->TBerangkat
#define TDatang(p) p->TDatang
#define TDurasi(p) p->TDurasi
#define TotalHarga(p) p->TotalHarga
#define NextPlg(p) p->NextPlg
#define FirstPnp(p) p->FirstPnp
#define NamaPenumpang(p) p->NamaPenumpang
#define Gelar(p) p->Gelar
#define Harga_1(p) p->Harga_1
#define NextPnp(p) p->NextPnp
#define KodeAsal(p) p->KodeAsal
#define KodeTujuan(p) p->KodeTujuan
#define tmpEdge(p) p->tmpEdge
#define no_transit(p) p->no_transit
#define NextPTransit(p) p->NextPTransit
#define FirstTransit(p) p->FirstTransit
#define tempEdge(p) p->tempEdge
#define NextTransit(p) p->NextTransit
#define WaktuBerangkat(p) p->WaktuBerangkat
#define tmpDFS(p) p->tmpDFS

#define NextTDFS(p) p->NextTDFS


#define Nama_Pemesan(p) p->Nama_Pemesan
#define No_HANDPHONE(p) p->No_HANDPHONE
#define Jadwal_FIGHT(p) p->Jadwal_FIGHT
#define penumpang_T(p) p->penumpang_T
#define NextPeTRS(p) p->NextPeTRS
#define JDtransit(p) p->JDtransit
#define NextJP(p) p->NextJP
#define Nama_Penumpang(p) p->Nama_Penumpang
#define Gelar_Penumpang(p) p->Gelar_Penumpang
#define NextTPNT(p) p->NextTPNT
#define tempEdgeJP(p) p->tempEdgeJP
#define WaktuBerangkatJP(p) p->WaktuBerangkatJP
#define DepartureJP(p) p->DepartureJP
#define KodeDprJP(p) p->KodeDprJP
#define ArrivalJP(p) p->ArrivalJP
#define KodeArvJP(p) p->KodeArvJP
#define NamaPesawatJP(p) p->NamaPesawatJP
#define KodePesawatJP(p) p->KodePesawatJP
#define TimedepartureJP(p) p->TimedepartureJP
#define TimearrivalJP(p) p->TimearrivalJP
#define DurasiJP(p) p->DurasiJP
#define HargaJP(p) p->HargaJP
#define visited(p) p->visited
#define cVisited(p) p->cVisited
#define NextVstd(p) p->NextVstd


